global:
  contract_device_count: 60
projects:
  defaults:
    # TODO: start using USER_SCRIPTS_VERSION for git version? name repo `mozilla-lambdatest-files`?
    # for now this points to a directory name in `mozilla_bitbar_devicepool/lambdatest/user_scripts`
    USER_SCRIPTS_VERSION: v3-disable-adb-killserver
    # fake values. inheriting projects below should set reasonable values.
    TASKCLUSTER_CLIENT_ID: tc-client-id-set-me
    # env var with key is looked for at this with underscores: `tc_worker_type_set_me`
    TC_WORKER_TYPE: tc-worker-type-set-me
    disabled: false
    priority_group: set-a-priority-group
    priority: 1
  a55-alpha:
    # used for relops testing
    # TODO: decomm this in favor of test-1, name is confusing given usage in cloud image context
    TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-lambda-alpha-a55
    TC_WORKER_TYPE: gecko-t-lambda-alpha-a55
    USER_SCRIPTS_VERSION: v4-python313
    priority_group: a55
    priority: 10
  a55-perf:
    TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-lambda-perf-a55
    TC_WORKER_TYPE: gecko-t-lambda-perf-a55
    priority_group: a55
  p9-perf:
    TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-lambda-perf-p9
    TC_WORKER_TYPE: gecko-t-lambda-perf-p9
    priority_group: p9
  # test-1:
  #     SCRIPT_REPO_COMMIT: future_commit
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-lambda-test-1
  #     TC_WORKER_TYPE: gecko-t-lambda-gw-test-1
  #     # override SCRIPT_REPO_COMMIT with a test commit
device_groups:
  a55-perf:
    # devices with power meters
    RZCX821GXDJ:  # 9/10/25: previously recabled and verified by jmaher
    RZCY10LGB6W:  # 9/10/25: previously recabled and verified by jmaher
    RZCY10Y4HWD:  # 9/10/25: previously recabled and verified by jmaher
    RZCY10Y4QVX:  # 9/10/25: previously recabled and verified by jmaher
    RZCY10Y4TAV:  # 9/10/25: previously recabled and verified by jmaher
    RZCY10Y4TJX:  # 9/10/25: previously recabled and verified by jmaher
    R5CXC1ASLHH:  # 9/10/25: recabled and verified by jmaher
    R5CXC1AHV4M:  # 9/10/25: recabled and verified by jmaher
    R5CXC1ASA0L:  # 9/10/25: recabled and verified by jmaher
    R5CXC1ASA3P:  # 9/11/25: recabled and verified by jmaher
    R5CXC1AP2KT:  # 9/11/25: recabled and verified by jmaher
    R5CXC1HZK0W:  # 9/11/25: recabled and verified by jmaher
    R5CXC1ASA2E:  # 9/11/25: recabled and verified by jmaher
    R5CXC1ARM0A:  # 9/11/25: recabled and verified by jmaher
    RZCY2011M7N:  # 9/11/25: recabled and verified by jmaher
    RZCY203N75Z:  # 9/15/25: recabled and verified by jmaher
    # devices on 10.146.2.48
    R5CXC1AMNFY:  # 9/15/25: recabled and verified by jmaher
    RZCX31FDGJE:  # 9/15/25: recabled and verified by jmaher
    R5CY21T22NH:  # 9/15/25: recabled and verified by jmaher
    RZCX71ZVF6J:  # 9/15/25: recabled and verified by jmaher
    RZCX821GYPX:  # 9/15/25: recabled and verified by jmaher
    RZCY204AAZD:  # 9/15/25: recabled and verified by jmaher
    # devices on 10.146.2.54 and 10.146.2.53
    R5CXC1ASH4E:  # 9/16/25: recabled and verified by jmaher
    RZCXC16WHTA:  # 9/16/25: recabled and verified by jmaher
    R5CXC1AHZBW:  # 9/16/25: recabled and verified by jmaher
    RZCXC189JSJ:  # 9/16/25: recabled and verified by jmaher
    R5CXC1PW7CR:  # 9/16/25: recabled and verified by jmaher
    R5CXC1PW94F:  # 9/16/25: recabled and verified by jmaher
    RZCXC187YCR:  # 9/16/25: recabled and verified by jmaher
    RZCXC16W6KT:  # 9/16/25: recabled and verified by jmaher
    # devices on 10.146.2.55
    R5CXC1ARZDN:  # 9/17/25: recabled and verified by jmaher
    R5CXC1HZ43J:  # 9/17/25: recabled and verified by jmaher
    R5CXC1HZ85W:  # 9/17/25: recabled and verified by jmaher
    R5CXC1HZA6V:  # 9/17/25: recabled and verified by jmaher
    R5CXC1SXMVR:  # 9/17/25: recabled and verified by jmaher
    RZCXC19G1DM:  # 9/17/25: recabled and verified by jmaher
    RZCXC1BK67D:  # 9/17/25: recabled and verified by jmaher
    RZCY107MCLV:  # 9/17/25: recabled and verified by jmaher
    R5CXC1HZKLR:  # 9/18/25: recabled and verified by jmaher
    R5CXC1ALFED:  # 9/18/25: recabled and verified by jmaher
    R5CXC1ARCER:  # 9/18/25: recabled and verified by jmaher
    R5CXC1ANGLT:  # 9/19/25: recabled and verified by jmaher
    R5CXC1ASHNJ:  # 9/30/25: was quarantined, but reseated and power cycled and tested by jmaher as good
    R5CXC1HZ4KD:  # 9/30/25: was quarantined, but reseated and power cycled and tested by jmaher as good
    RZCXC15YZVZ:  # 9/30/25: was quarantined, but reseated and power cycled and tested by jmaher as good
    R5CXC1HZ5PZ:  # 9/30/25: was quarantined, but reseated and power cycled and tested by jmaher as good
    R5CXC1AHXYD:  # 9/30/25: was quarantined, but reseated and power cycled and tested by jmaher as good
    RZCXC19G1CT:  # 9/30/25: was quarantined, but reseated and power cycled and tested by jmaher as good
    R5CXC1AMMNK:  # 10/1/25: was reseated, power cycled, and verified by jmaher
    R5CXC1ARELR:  # 10/1/25: was reseated, power cycled, and verified by jmaher
    RZCY10Y548K:  # 10/1/25: was reseated, power cycled, and verified by jmaher
    R5CX4089QNL:  # 10/1/25: was reseated, power cycled, and verified by jmaher
  a55-alpha:
    RZCX50TW03H:  # on 10.146.2.48
    R5CXC1HZ62Y:  # devices that did not have power meters, qualify
    R5CXC1AHWWZ:  # 9/29/25: quarantined device batch 1, has been reseated and powered off/on. now test
    R5CXC1AJ02Z:  # 9/29/25: quarantined device batch 1, has been reseated and powered off/on. now test
    R5CXC1AJ07K:  # 9/29/25: quarantined device batch 1, has been reseated and powered off/on. now test
    RZCXC19G2SH:  # 9/29/25: quarantined device batch 1, has been reseated and powered off/on. now test
    RZCY10Y4TBY:  # 9/29/25: quarantined device batch 1, has been reseated and powered off/on. now test
  a55-sheriff-bad:
  p9-perf:
    # devices with power meters, have been recabled
    47160DLAQ003UB:
    47241FDAQ0016Y:
    47241FDAQ002C0:
  test-1:
    # no devices yet
