global:
  contract_device_count: 60
projects:
  defaults:
    SCRIPT_REPO_COMMIT: master
    # fake values. inheriting projects below should set reasonable values.
    TASKCLUSTER_CLIENT_ID: tc-client-id-set-me
    # env var with key is looked for at this with underscores: `tc_worker_type_set_me`
    TC_WORKER_TYPE: tc-worker-type-set-me
  a55-alpha:
    TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-lambda-alpha-a55
    TC_WORKER_TYPE: gecko-t-lambda-alpha-a55
  a55-perf:
    TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-lambda-perf-a55
    TC_WORKER_TYPE: gecko-t-lambda-perf-a55
  p9-perf:
    TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-lambda-perf-p9
    TC_WORKER_TYPE: gecko-t-lambda-perf-p9
  # test-1:
  #     SCRIPT_REPO_COMMIT: future_commit
  #     TASKCLUSTER_CLIENT_ID: project/autophone/gecko-t-lambda-test-1
  #     TC_WORKER_TYPE: gecko-t-lambda-gw-test-1
  #     # override SCRIPT_REPO_COMMIT with a test commit
device_groups:
  a55-perf:
    R5CX4089QNL
    R5CXC1AHV4M
    R5CXC1ALFED
    R5CXC1AMMNK
    R5CXC1AMNFY
    R5CXC1ANGLT
    R5CXC1AP2KT
    R5CXC1ARCER
    R5CXC1ARELR
    R5CXC1ARM0A
    R5CXC1ASA0L
    R5CXC1ASA2E
    R5CXC1ASA3P
    R5CXC1ASLHH
    R5CXC1HZK0W
    R5CY21T22NH
    RZCX31FDGJE
    RZCX50TW03H
    RZCX71ZVF6J
    RZCX821GXDJ
    RZCX821GYPX
    RZCY10LGB6W
    RZCY10Y4HWD
    RZCY10Y4QVX
    RZCY10Y4TAV
    RZCY10Y4TBY
    RZCY10Y4TJX
    RZCY10Y548K
    RZCY203N75Z
    RZCY204AAZD
    # second batch of devices for second part of contract
    # R5CXC1AHWWZ
    # R5CXC1AHXYD
    # R5CXC1AHZBW
    # R5CXC1AJ02Z
    # R5CXC1AJ07K
    # R5CXC1ARZDN
    # R5CXC1ASH4E
    # R5CXC1ASHNJ
    # R5CXC1HZ43J
    # R5CXC1HZ4KD
    # R5CXC1HZ5PZ
    # R5CXC1HZ62Y
    # R5CXC1HZ85W
    # R5CXC1HZA6V
    # R5CXC1PW7CR
    # R5CXC1PW94F
    # R5CXC1SXMVR
    # RZCXC15YZVZ
    # RZCXC16W6KT
    # RZCXC16WHTA
    # RZCXC187YCR
    # RZCXC189JSJ
    # RZCXC19G1CT
    # RZCXC19G1DM
    # RZCXC19G2SH
    # RZCXC1BK67D
    # RZCY107MCLV
  a55-alpha:
    # devices with power meters
    R5CXC1HZKLR
    RZCY2011M7N
  pixel9-perf:
    47160DLAQ003UB
    47241FDAQ0016Y
    47241FDAQ002C0
  test-1:
    # no devices yet
